### ISSUE TITLE
trying to add this to my project

### ISSUE THREAD

**Issue by shoshRose** [long2know/angular-directives-general#1]
Hi there!
I wanted to add this to a project I'm working on.
I am getting this error all the time: 

> Unknown provider: $uibPositionProvider <- $uibPosition <- multiselectDirective

console shows js file is loaded and exists. Can you help me with this? Thanks in advance.
-Shosh,

**Comment by long2know** [comment]
Look at the the demo folder for any directive you're importing into your project. I generally put all dependencies as CDN refs. It sounds like you're missing a reference to angular ui bootstrap.

**Comment by shoshRose** [comment]
This is very weird.. can't get it to work. I have all the dependencies..
I am using angular 1.2.21 bootstrap 3.3.2 and angular-ui 0.4.0
Are these versions compatible with your code?

**Comment by long2know** [comment]
I'm not sure if you have a reason to be using a very old version of Angular, but I can't speak to compatibility below version 1.3.  I know there were some breaking changes going from 1.2 -> 1.3 and some other libraries like angular-ui bootstrap may require 1.3+.  Although, I would recommend using the very latest versions of all libraries.

That brings me to another thing to check though.  The dependencies, specifically, and you can see this in **any of the demo plunkers**, are:
- Angular
- Angular modules:  loader, sanitize, animate
- Angular UI (if you want it to work w/ IE, angular ui IEShiv)
- Angular UI Router
- Angular UI Bootstrap (0.14.3 min)
- Bootstrap CSS

**Comment by shoshRose** [comment]
Unfortunately I have to use angular 1.2.
I did check all the dependencies I saw in the Plunkers. 
I appreciate your help very much!

**Comment by long2know** [comment]
According to the Angular team the version of Angular UI Bootstrap requires at least 1.3.x.  I believe I am using 0.14.3.

**_0.14.3 is the last version of this library that supports AngularJS 1.3.x_**

https://angular-ui.github.io/bootstrap/
