### ISSUE TITLE
Multiselect does not work with angular 1.5

### ISSUE THREAD

**Issue by mgalic** [long2know/angular-directives-general#2]
Thank you for really nice and useful directive. Can you update it to work with latest angular 1.x and ui-bootstrap?

**Comment by mgalic** [comment]
There was only one dependency which I had to update to make it work for me. Instead of $position I changed it to $uibPosition and it works. Maybe it helps somebody.

**Comment by long2know** [comment]
Odd - I don't think I have any differences between my work branch and the branch here.  It already references $uibPosition and works, at least, with Angular 1.5.7..

**Comment by long2know** [comment]
To double check, I opened the demo plunker (https://long2know.com/2016/05/angular-multiselect-dropdown-updated/) and only changed all of the references to Angular to use v.1.5.7.  It works without incident.
