### ISSUE TITLE
Model not getting refreshed when the underlying Options is changed.

### ISSUE THREAD

**Issue by jkshan** [long2know/angular-directives-general#3]
I want to populate the underlying options dynamically, based on some condition, the Options list is getting refreshed as per the dynamic conditions, but the underlying Model doesn't refresh based on the new Options available.

You can view it in the plunker here (http://plnkr.co/edit/g4m8zY93S5Jycm86t7JS?p=preview), 
 1. Select the Options from 6-10, 
 2. Then Uncheck the Checkbox, this will reduce the options 5 items, 

Issue: But the model remains the same even though those items are no more available for de-select.

**Comment by long2know** [comment]
Good catch - I had always anticipated that the ngModel options would always exist in the list, so did nothing special if the underlying list changed.

Fortunately, this was a pretty easy change.  In the watcher that is watching the "options," I added a call to the method that sets ngModel based on the values in ngModel and what exists in the "options."

Another way to handle this, though, would be to clear out your ngModel directly (vm.option1.length = 0)
