### ISSUE TITLE
API to get the Un-Checked items.

### ISSUE THREAD

**Issue by jkshan** [long2know/angular-directives-general#4]
Hi,

Is there any possibility to expose an option to hook up a function to get the Un-checked items during drop-down close event?

Thanks.

**Comment by long2know** [comment]
It is possible. There are (2) ways the dropdown can close. You’ll find a “clickHandler” that is called when clicking outside of the multiselect which causes closing and a toggleSelect method which toggles the state of the dropdown through clicking the multiselect button. You would only need to pass in a callback handler/attribute and evaluate it in both of the popup closing routines. Alternatively, you can use the standard ng-change directive that will be triggered whenever the bound model is changed. If you want unselected items, it would be the items that are not in the selected list. A $filter could derive this. Let me know if that helps.

To expand upon that comment, the clickHandler could receive the items list that is internal to the multiselect.  Those items have a simple boolean indicating 'isSelected' status.  I can look into attaching a "closeHandler" and "openHandler" attributes that can receive all items.  If that's useful.

Another possibility is to add the "ng-change" attribute if you are only interested in getting unselected items.  That goes back to a $filter approach.  Although, it would fire every time something is selected/deselected.
